### ISSUE TITLE
MFA Support

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.hrobot#128]
##### SUMMARY
We've setup MFA (TOTP) on our hetzner Account. How to use `community.hrobot` using MFA?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

e.g. community.hrobot.firewall 

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/m/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/m/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True

```

**Comment by markuman** [comment]
[Check that Hetzner returns 2FA info message](https://github.com/aszlig/hetzner/issues/24)

**Comment by felixfontein** [comment]
The collection doesn't support it at the moment. I don't even know how it would work, the docs (https://robot.hetzner.com/doc/webservice/en.html#general) don't mention it *at all*.

**Comment by markuman** [comment]
Ok, it does not support MFA. Furthermore, for hrobot API Usage, you must create a separate User. I would call like very likely to a key and secret pair, because the username is randomized characters.

> To be able to use the interface, a web service user is required. You can create this user in Robot via the user menu in the upper right corner under "Settings" -> "Web service and app settings".

https://robot.hetzner.com/doc/webservice/en.html#preface
