### ISSUE TITLE
Failed to parse robot.yml "Invalid empty host name provided"

### ISSUE THREAD

**Issue by kebl-reflact** [ansible-collections/community.hrobot#40]
##### SUMMARY
Hello, 

I am unable to parse my robot inventory file as discribed in the docs. 
I always get an empty response.
Failed to parse /home/**/github_ansible/inventory/test.robot.yml with ansible_collections.community.hrobot.plugins.inventory.robot plugin: Invalid empty host name provided: None
When I try with curl:
curl -u user:password https://robot-ws.your-server.de/server
i get the disered result.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Inventory Plugin community.hrobot.robot

##### ANSIBLE VERSION
```paste below
ansible --version
ansible [core 2.12.2]
  config file = /home/**/**/ansible.cfg
  configured module search path = ['/home/**/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/**/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True

```

##### COLLECTION VERSION
```paste below
ansible-galaxy collection list community.hrobot
# /home/**/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.hrobot 1.2.3  

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.hrobot 1.2.2  


ansible-galaxy collection verify community.hrobot 
Verifying 'community.hrobot:1.2.3'
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOLOR(/home/**/github_ansible/ansible.cfg) = False
CALLBACKS_ENABLED(/home/**/github_ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/**/github_ansible/ansible.cfg) = ['/home/**/github_ansible/inventory']
DEFAULT_REMOTE_USER(/home/**/github_ansible/ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(/home/**/github_ansible/ansible.cfg) = /**************
INVENTORY_ENABLED(/home/**/github_ansible/ansible.cfg) = ['community.hrobot.robot']
```

##### OS / ENVIRONMENT
WSL Ubuntu 20.04

##### STEPS TO REPRODUCE
Make a inventory test.robot.yml

```yaml
---
plugin: community.hrobot.robot
hetzner_password: ************
hetzner_user: ************
```
```
ansible-inventory -i test.robot.yml --list
```

##### EXPECTED RESULTS
Some kind of inventory

##### ACTUAL RESULTS

```paste below
# shortend output with errors
[WARNING]:  * Failed to parse /home/**/github_ansible/inventory/test.robot.yml with ansible_collections.community.hrobot.plugins.inventory.robot plugin: Invalid empty host name provided: None
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/**/.ansible/collections/ansible_collections/community/hrobot/plugins/inventory/robot.py", line 130, in parse
    self.populate(servers)
  File "/home/**/.ansible/collections/ansible_collections/community/hrobot/plugins/inventory/robot.py", line 142, in populate
    self.inventory.add_host(server_name)
  File "/usr/lib/python3/dist-packages/ansible/inventory/data.py", line 232, in add_host
    raise AnsibleError("Invalid empty host name provided: %s" % host)
[WARNING]: Unable to parse /home/**/github_ansible/inventory/test.robot.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

**Comment by felixfontein** [comment]
It seems that both the `server_name` and `server_ip` fields for one of your host are not present / `null` (`None` in Python). The code assumes that `server_ip` is always present and has content.

Is this maybe a dedicated server without an IPv4 address? Hetzner only recently allowed ordering such servers, and I haven't seen the API output for such an configuration yet.

**Comment by kebl-reflact** [comment]
Oh, I see, we have a Rack Reservation in our Robot. Which (at the Moment) has neither IP nor Name.
giving every Resource except of Colocation Racks a Name fixed it, now it works as intended.

Thank you very much vor the hint.

**Comment by felixfontein** [comment]
Interesting; I've never worked with colocation racks / rack reservations, so I've never seen that :) I still think the plugin shouldn't crash in that case though. It might be better to issue a warning that something could not be added to the inventory, or even make the behavior configurable somehow. Or even allow to extract the inventory name from other information (like using the integer ID).

**Comment by kebl-reflact** [comment]
Well the error kind of says it. But yeah more readable error would have saved me a rabbit hole.
The way the auto inventory from ansible works is, that it just says it can't use this inventory. 
The error I provided is only shown with -vvv, which lets you think it's not about the source info but rather the file, a plugin, collection requirement or whatever it is ansible is doing under the hood. 
While I think a rack reservation can (maybe?) be ignored I dont think a warning is sufficient here. I just testet by removing a name from our collocation rack and it fails again. Because it doesn't have an IP address.

I am aware that collocation and racks overall cannot really be interacted with at the moment but for completenes it would be nice.
